### ISSUE TITLE
Setup & test the routing to latest dotnet version

### ISSUE THREAD

**Issue by oserban** [ove/ove-asset-services#67]
```c#
services.AddMvc(options => {
    options.InputFormatters.Insert(0, new RawRequestBodyFormatter());
})
.SetCompatibilityVersion(CompatibilityVersion.Latest)
.AddXmlSerializerFormatters().AddJsonOptions(options => {
   options.SerializerSettings.Formatting = Formatting.Indented;
}).AddRazorPagesOptions( o=> {
         ...
});
}
```

**Comment by oserban** [comment]
This is currently not working with 2.2 as this version is in pre-release

**Comment by davidbirchwork** [comment]
for future reference: 

so... the bug is as follows in https://github.com/ove/ove-asset-services/blob/ef49c4fa6258bf26090249c669c12121f13f90eb/packages/ove-asset-manager/src/OVE.Service.AssetManager/Views/OVEAssetModel/GetRemovableView.cshtml#L36 we make a link to https://github.com/ove/ove-asset-services/blob/ef49c4fa6258bf26090249c669c12121f13f90eb/packages/ove-asset-manager/src/OVE.Service.AssetManager/Controllers/OVEAssetModelController.cs#L531 
The routing for this is automatically injected so that the web form gets the correct post route. 
however this is not happening under 2.2. and no route is being injected. 
I have a suspicion that this is partly responsible https://github.com/aspnet/AspNetCore/issues/4212

let us await the next pre-release or even RTM and then test again
